name: Maven Build

on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
          server-id: D4rK3oN_GitHub # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml
